# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0990c3ebbc1077b9b3ec7b4b9a60cd206105e6d260154634c4d0e9989dd55bb76cb6dd0ea393bceafff82a69bea67fe27e89e782521cce5bd66f5bced6a173e9

test:
  secret_key_base: ca51b99f70bf226b56e567d4cd84c7a791721f770a58d5552e97905b6573a8cd66fc1e9cd1015d53507539aef695770574e94a4571b618814522d2631e4881fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
